[package]
name = "gdt2dicom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
log = "0.4"
tempfile = "3.4.0"
xml-rs = "0.8.4"

[[bin]]
name = "dicom2gdt"
test = false
bench = false
