name: Build
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}
          RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu
      - name: Check format
        run: |
          cd ${{ github.workspace }}
          rustfmt --check src/**/*.rs
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Linux artifact
          path: |
            ./target/x86_64-unknown-linux-gnu/release/gdt2dicom
            ./target/x86_64-unknown-linux-gnu/release/dicom2gdt
            ./target/x86_64-unknown-linux-gnu/release/gdt2opp
            ./target/x86_64-unknown-linux-gnu/release/gdt2vdds
          retention-days: 5

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}
          cargo build --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Windows artifact
          path: |
            .\target\release\gdt2dicom.exe
            .\target\release\dicom2gdt.exe
            .\target\release\gdt2opp.exe
            .\target\release\gdt2vdds.exe
          retention-days: 5

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}
          cargo build --release
      - name: Check format
        run: |
          cd ${{ github.workspace }}
          rustfmt --check src/**/*.rs
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Mac Artifact
          path: |
            ./target/release/gdt2dicom
            ./target/release/dicom2gdt
            ./target/release/gdt2opp
            ./target/release/gdt2vdds
          retention-days: 5
