name: Build
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgtk-4-dev build-essential
          pkg-config --modversion gtk4
          pkg-config --cflags gtk4
          pkg-config --libs gtk4
      - name: Build
        run: |
          cd ${{ github.workspace }}
          RUSTFLAGS='-C target-feature=+crt-static' cargo build --verbose --release --target x86_64-unknown-linux-gnu --bin gdt2dicom --bin dicom2gdt --bin gdt2opp --bin gdt2vdds
          cargo build --verbose --release --target x86_64-unknown-linux-gnu --bin gui
      - name: Check format
        run: |
          cd ${{ github.workspace }}
          rustfmt --check src/**/*.rs
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Linux artifact
          path: |
            ./target/x86_64-unknown-linux-gnu/release/gdt2dicom
            ./target/x86_64-unknown-linux-gnu/release/dicom2gdt
            ./target/x86_64-unknown-linux-gnu/release/gdt2opp
            ./target/x86_64-unknown-linux-gnu/release/gdt2vdds
            ./target/x86_64-unknown-linux-gnu/release/gui
          retention-days: 5

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          choco install msys2 visualstudio2022-workload-vctools python312 pkgconfiglite gtk-runtime
          py -3.12 -m pip install --user pipx
          py -3.12 -m pipx ensurepath
          pipx install gvsbuild
          gvsbuild build gtk4
      - name: Build
        run: |
          cd ${{ github.workspace }}
          $env:PKG_CONFIG_PATH="/mingw64/lib/pkgconfig;/mingw64/share/pkgconfig;C:/gtk-build/gtk/x64/release/lib/pkgconfig"
          cargo build --verbose --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Windows artifact
          path: |
            .\target\release\gdt2dicom.exe
            .\target\release\dicom2gdt.exe
            .\target\release\gdt2opp.exe
            .\target\release\gdt2vdds.exe
          retention-days: 5
      - name: Copy GUI dependencies
        run: |
          mkdir gui-out
          cp .\target\release\gui.exe ./gui-out/
          git clone https://github.com/B00merang-Project/Windows-10.git
          cp C:/gtk-build/gtk/x64/release/bin/cairo-2.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/harfbuzz.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/fribidi-0.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/cairo-gobject-2.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/gdk_pixbuf-2.0-0.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/epoxy-0.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/zlib1.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/graphene-1.0-0.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/pangowin32-1.0-0.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/iconv.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/libpng16.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/tiff.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/jpeg62.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/cairo-script-interpreter-2.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/freetype-6.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/pixman-1-0.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/gio-2.0-0.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/glib-2.0-0.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/gobject-2.0-0.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/gtk-4-1.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/ffi-8.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/intl.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/pcre2-8-0.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/gmodule-2.0-0.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/pangocairo-1.0-0.dll ./gui-out/
          cp C:/gtk-build/gtk/x64/release/bin/pango-1.0-0.dll ./gui-out/
          mkdir -p ./gui-out/share/
          cp -R C:/gtk-build/gtk/x64/release/share/locale ./gui-out/share/
          cp -R C:/gtk-build/gtk/x64/release/share/thumbnailers ./gui-out/share/
          cp -R C:/gtk-build/gtk/x64/release/share/glib-2.0 ./gui-out/share/
          cp -R C:/gtk-build/gtk/x64/release/share/gtk-4.0 ./gui-out/share/
          mkdir -p ./gui-out/share/themes/Windows10/
          cp -R ./Windows-10/gtk-4.0 ./gui-out/share/themes/Windows10/
          mkdir -p ./gui-out/etc/gtk-4.0/
          echo '[Settings]' >> ./gui-out/etc/gtk-4.0/settings.ini
          echo 'gtk-theme-name=Windows10' >> ./gui-out/etc/gtk-4.0/settings.ini
          echo 'gtk-font-name=Segoe UI 9' >> ./gui-out/etc/gtk-4.0/settings.ini

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: GUI out
          path: |
            .\gui-out

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew install gtk4
      - name: Build
        run: |
          cd ${{ github.workspace }}
          cargo build --release
      - name: Check format
        run: |
          cd ${{ github.workspace }}
          rustfmt --check src/**/*.rs
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Mac Artifact
          path: |
            ./target/release/gdt2dicom
            ./target/release/dicom2gdt
            ./target/release/gdt2opp
            ./target/release/gdt2vdds
            ./target/release/gui
          retention-days: 5
