name: Build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}
          cargo build --release
      - name: Check format
        run: |
          cd ${{ github.workspace }}
          rustfmt --check src/*.rs
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            ./target/release/gdt2dicom
          retention-days: 5
