name: Publish Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}
          cargo build --release
          tar -czvf gdt2dicom-linux.tar.gz ./target/release/gdt2dicom
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            gdt2dicom-linux.tar.gz

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}
          cargo build --release
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            .\target\release\gdt2dicom.exe

  build-mac:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}
          cargo build --release
          tar -czvf gdt2dicom-mac.tar.gz ./target/release/gdt2dicom
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            gdt2dicom-mac.tar.gz
