name: Publish Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}
          cargo build --release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ./target/release/gdt2dicom
