name: Publish Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}
          RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu
          tar -czvf gdt2dicom-linux.tar.gz ./target/x86_64-unknown-linux-gnu/release/gdt2dicom
          tar -czvf dicom2gdt-linux.tar.gz ./target/x86_64-unknown-linux-gnu/release/dicom2gdt
          tar -czvf gdt2opp-linux.tar.gz ./target/x86_64-unknown-linux-gnu/release/gdt2opp
          tar -czvf gdt2vdds-linux.tar.gz ./target/x86_64-unknown-linux-gnu/release/gdt2vdds
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            gdt2dicom-linux.tar.gz
            dicom2gdt-linux.tar.gz
            gdt2opp-linux.tar.gz
            gdt2vdds-linux.tar.gz

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}
          cargo build --release
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            .\target\release\gdt2dicom.exe
            .\target\release\dicom2gdt.exe
            .\target\release\gdt2opp.exe
            .\target\release\gdt2vdds.exe

  build-mac:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd ${{ github.workspace }}
          cargo build --release
          tar -czvf gdt2dicom-mac.tar.gz ./target/release/gdt2dicom
          tar -czvf dicom2gdt-mac.tar.gz ./target/release/dicom2gdt
          tar -czvf gdt2opp-mac.tar.gz ./target/release/gdt2opp
          tar -czvf gdt2vdds-mac.tar.gz ./target/release/gdt2vdds
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            gdt2dicom-mac.tar.gz
            dicom2gdt-mac.tar.gz
            gdt2opp-mac.tar.gz
            gdt2vdds-mac.tar.gz
